"""Embedded template content for sdd-cli."""

SPECIFICATION_TEMPLATE = """\
# Feature Specification: [FEATURE NAME]

**Created**: [DATE]
**Status**: Draft
**Input**: User description: "$ARGUMENTS"

## User Scenarios & Testing *(mandatory)*

<!--
  IMPORTANT: User stories should be PRIORITIZED as user journeys ordered by importance.
  Each user story/journey must be INDEPENDENTLY TESTABLE - meaning if you implement just
  ONE of them, you should still have a viable MVP that delivers value.

  Assign priorities (P1, P2, P3, etc.) to each story, where P1 is the most critical.
-->

### User Story 1 - [Brief Title] (Priority: P1)

[Describe this user journey in plain language]

**Why this priority**: [Explain the value and why it has this priority level]

**Independent Test**: [Describe how this can be tested independently]

**Acceptance Scenarios**:

1. **Given** [initial state], **When** [action], **Then** [expected outcome]
2. **Given** [initial state], **When** [action], **Then** [expected outcome]

---

### User Story 2 - [Brief Title] (Priority: P2)

[Describe this user journey in plain language]

**Why this priority**: [Explain the value and why it has this priority level]

**Independent Test**: [Describe how this can be tested independently]

**Acceptance Scenarios**:

1. **Given** [initial state], **When** [action], **Then** [expected outcome]

---

### User Story 3 - [Brief Title] (Priority: P3)

[Describe this user journey in plain language]

**Why this priority**: [Explain the value and why it has this priority level]

**Independent Test**: [Describe how this can be tested independently]

**Acceptance Scenarios**:

1. **Given** [initial state], **When** [action], **Then** [expected outcome]

---

[Add more user stories as needed, each with an assigned priority]

### Edge Cases

- What happens when [boundary condition]?
- How does system handle [error scenario]?

## Requirements *(mandatory)*

### Functional Requirements

- **FR-001**: System MUST [specific capability]
- **FR-002**: System MUST [specific capability]
- **FR-003**: Users MUST be able to [key interaction]

### Key Entities *(include if feature involves data)*

- **[Entity 1]**: [What it represents, key attributes without implementation]
- **[Entity 2]**: [What it represents, relationships to other entities]

## Success Criteria *(mandatory)*

### Measurable Outcomes

- **SC-001**: [Measurable metric, e.g., "Users can complete the task in under 2 minutes"]
- **SC-002**: [Measurable metric, e.g., "System handles 1000 concurrent users"]
- **SC-003**: [User satisfaction metric]
"""

PLAN_TEMPLATE = """\
# Implementation Plan: [FEATURE]

**Date**: [DATE] | **Spec**: [link to spec.md]
**Input**: Feature specification from `.sdd/[feature-dir]/spec.md`

## Summary

[Extract from feature spec: primary requirement + technical approach from research]

## Technical Context

**Language/Version**: [e.g., Python 3.10, TypeScript 5.x, or NEEDS CLARIFICATION]
**Primary Dependencies**: [e.g., FastAPI, React, or NEEDS CLARIFICATION]
**Storage**: [if applicable, e.g., PostgreSQL, files, or N/A]
**Testing**: [e.g., pytest, Jest, or NEEDS CLARIFICATION]
**Target Platform**: [e.g., Linux server, browser, mobile, or NEEDS CLARIFICATION]
**Project Type**: [e.g., library/cli/web-service/mobile-app or NEEDS CLARIFICATION]
**Performance Goals**: [domain-specific or NEEDS CLARIFICATION]
**Constraints**: [e.g., <200ms p95, <100MB memory, offline-capable or NEEDS CLARIFICATION]
**Scale/Scope**: [e.g., 10k users, single developer tool, or NEEDS CLARIFICATION]

## Project Structure

### Documentation (this feature)

```text
.sdd/[feature-dir]/
├── spec.md        # Feature specification
├── plan.md        # This file
├── research.md    # Phase 0 output (optional)
├── data-model.md  # Phase 1 output (optional)
├── contracts/     # Phase 1 output (optional)
└── tasks.md       # Generated by /sdd.tasks command
```

### Source Code (repository root)

```text
src/
├── models/
├── services/
└── [feature-specific modules]

tests/
├── unit/
└── integration/
```

**Structure Decision**: [Document the selected structure with real directories]

## Research Findings

[Document key technical decisions, alternatives considered, and rationale]

### Decision: [Topic]

- **Chosen**: [What was selected]
- **Rationale**: [Why]
- **Alternatives considered**: [What else was evaluated]

## Data Model

[Key entities, relationships, and validation rules — or reference data-model.md if generated]

## Interface Contracts

[Public interfaces the feature exposes — or reference contracts/ directory if generated]
"""

TASKS_TEMPLATE = """\
# Tasks: [FEATURE NAME]

**Input**: Design documents from `.sdd/[feature-dir]/`
**Prerequisites**: plan.md (required), spec.md (required for user stories)

## Format: `- [ ] T### [P?] [Story] Description`

- **[P]**: Can run in parallel (different files, no dependencies)
- **[Story]**: Which user story this task belongs to (e.g., US1, US2, US3)
- Include exact file paths in descriptions

## Phase 1: Setup

**Purpose**: Project initialization and basic structure

- [ ] T001 Create project structure per implementation plan
- [ ] T002 Initialize project with required dependencies
- [ ] T003 [P] Configure linting and formatting tools

---

## Phase 2: Foundational

**Purpose**: Core infrastructure that MUST be complete before ANY user story

**⚠️ CRITICAL**: No user story work can begin until this phase is complete

- [ ] T004 Setup core infrastructure (database, auth, etc.)
- [ ] T005 [P] Implement shared utilities
- [ ] T006 Configure error handling and logging

**Checkpoint**: Foundation ready — user story implementation can now begin

---

## Phase 3: User Story 1 - [Title] (Priority: P1) 🎯 MVP

**Goal**: [Brief description of what this story delivers]

**Independent Test**: [How to verify this story works on its own]

- [ ] T007 [P] [US1] Create [Entity1] model in src/models/[entity1].py
- [ ] T008 [P] [US1] Create [Entity2] model in src/models/[entity2].py
- [ ] T009 [US1] Implement [Service] in src/services/[service].py
- [ ] T010 [US1] Implement [feature] in src/[location]/[file].py
- [ ] T011 [US1] Add validation and error handling

**Checkpoint**: User Story 1 fully functional and independently testable

---

## Phase 4: User Story 2 - [Title] (Priority: P2)

**Goal**: [Brief description]

**Independent Test**: [How to verify this story works on its own]

- [ ] T012 [P] [US2] Create [Entity] model in src/models/[entity].py
- [ ] T013 [US2] Implement [Service] in src/services/[service].py
- [ ] T014 [US2] Implement [feature] in src/[location]/[file].py

**Checkpoint**: User Stories 1 AND 2 work independently

---

[Add more user story phases as needed]

---

## Phase N: Polish

- [ ] TXXX [P] Documentation updates
- [ ] TXXX Code cleanup and refactoring
- [ ] TXXX Security hardening

---

## Dependencies & Execution Order

- **Setup → Foundational → User Stories (in parallel) → Polish**
- User stories depend only on Foundational completion; they can run in parallel
- Within each story: Models → Services → Endpoints → Integration
"""

SPECIFICATION_CHECKLIST_TEMPLATE = """\
# Specification Quality Checklist: [FEATURE NAME]

**Purpose**: Validate specification completeness before proceeding to planning
**Created**: [DATE]
**Feature**: [Link to spec.md]

## Content Quality

- [ ] No implementation details (languages, frameworks, APIs)
- [ ] Focused on user value and business needs
- [ ] Written for non-technical stakeholders
- [ ] All mandatory sections completed

## Requirement Completeness

- [ ] No [NEEDS CLARIFICATION] markers remain
- [ ] Requirements are testable and unambiguous
- [ ] Success criteria are measurable
- [ ] Success criteria are technology-agnostic
- [ ] All acceptance scenarios are defined
- [ ] Edge cases are identified
- [ ] Scope is clearly bounded

## Feature Readiness

- [ ] All functional requirements have clear acceptance criteria
- [ ] User scenarios cover primary flows
- [ ] Feature meets measurable outcomes defined in Success Criteria

## Notes

- Items marked incomplete require spec updates before `/sdd.plan`
"""

_TEMPLATE_REGISTRY: dict[str, dict[str, str]] = {
    "specification": {
        "content": SPECIFICATION_TEMPLATE,
        "description": "Feature specification template with user stories and requirements",
    },
    "plan": {
        "content": PLAN_TEMPLATE,
        "description": "Implementation plan template with technical context and design artifacts",
    },
    "tasks": {
        "content": TASKS_TEMPLATE,
        "description": "Actionable task list template organized by user story",
    },
    "specification-checklist": {
        "content": SPECIFICATION_CHECKLIST_TEMPLATE,
        "description": "Quality checklist for validating feature specifications",
    },
}

_TEMPLATES: dict[str, str] = {
    name: meta["content"] for name, meta in _TEMPLATE_REGISTRY.items()
}

_DESCRIPTIONS: dict[str, str] = {
    name: meta["description"] for name, meta in _TEMPLATE_REGISTRY.items()
}


def get_template(name: str) -> str:
    """Return template content by name, or raise KeyError if not found."""
    return _TEMPLATES[name]


def list_templates() -> list[tuple[str, str]]:
    """Return list of (name, description) tuples for all available templates."""
    return [(name, _DESCRIPTIONS[name]) for name in _TEMPLATES]
